# Generated by Django 5.1.2 on 2024-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
