# Generated by Django 5.1.2 on 2024-11-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_itemvariants'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='variants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.itemvariants'),
            preserve_default=False,
        ),
    ]
