# Generated by Django 5.1.2 on 2024-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='variants',
        ),
        migrations.AddField(
            model_name='item',
            name='variants',
            field=models.ManyToManyField(to='shop.itemvariants'),
        ),
    ]
